import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of Trainix.",
};

const LAST_UPDATED = "August 18, 2026";

export default function TermsPage() {
  return (
    <article className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-strong sm:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted">Last updated: {LAST_UPDATED}</p>
      </div>

      <Section title="1. Agreement to these terms">
        <p>These Terms of Service ("Terms") govern your access to and use of Trainix (the "Service"), including our website, apps, and the AI-generated fitness and nutrition features we provide. By creating an account or otherwise using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.</p>
      </Section>

      <Section title="2. Who can use Trainix">
        <p>You must be at least 16 years old to create an account. By registering, you confirm the information you provide (including your date of birth) is accurate, and that you are creating the account for yourself and not on behalf of someone else without their consent.</p>
      </Section>

      <Section title="3. Your account">
        <p>You're responsible for keeping your login credentials confidential and for all activity that happens under your account. Tell us right away if you suspect unauthorized access. We may suspend or terminate accounts that violate these Terms, provide false information, or are used to abuse the Service.</p>
      </Section>

      <Section title="4. Health, fitness, and AI-generated content">
        <p><strong>Trainix is not a medical device, and nothing in the Service is medical advice.</strong> Workout plans, nutrition plans, and body-composition estimates are generated by AI models based on the information and photos you provide, and are intended for general fitness guidance only. They are not a substitute for advice from a qualified physician, registered dietitian, or other healthcare professional.</p>
        <p>Talk to a doctor before starting any new exercise or nutrition program, especially if you have an existing health condition, injury, or are pregnant. Stop any activity that causes pain, dizziness, or discomfort. You use the Service's recommendations at your own risk.</p>
        <p>AI-generated content can be inaccurate or incomplete. We don't guarantee that any plan, estimate, or piece of advice generated by the Service is correct, complete, or suitable for your specific circumstances.</p>
      </Section>

      <Section title="5. Photos and body-scan analysis">
        <p>If you upload a photo for body-composition analysis, you confirm it's a photo of yourself (or of someone who has given you permission to upload it on their behalf) and that you have the right to share it with us. We use uploaded photos only to generate your personal analysis and are not displayed publicly. See our <a className="link" href="/privacy">Privacy Policy</a> for how photos are stored and processed.</p>
      </Section>

      <Section title="6. Subscriptions and billing">
        <p>Some features of Trainix require a paid subscription. If you subscribe, you authorize us (and our payment processor) to charge your chosen payment method on a recurring basis until you cancel. Prices, billing periods, and included features are shown at the time of purchase and may change with notice. You can cancel anytime from your account settings; cancellation takes effect at the end of the current billing period, and we don't provide partial refunds for unused time except where required by law.</p>
      </Section>

      <Section title="7. Acceptable use">
        <p>Don't use Trainix to: violate any law; upload content you don't have the rights to; attempt to access another user's account or data; interfere with or disrupt the Service (including its infrastructure); scrape or bulk-extract data; or reverse-engineer the Service beyond what applicable law allows.</p>
      </Section>

      <Section title="8. Your content">
        <p>You retain ownership of the photos, measurements, and other content you submit. By submitting it, you grant us a limited license to store and process it solely to provide the Service to you (for example, to generate your plans and analysis). We don't sell your personal content.</p>
      </Section>

      <Section title="9. Termination">
        <p>You can delete your account at any time from your profile settings; this permanently removes your plans, measurements, and notifications. We may suspend or terminate your access if you violate these Terms.</p>
      </Section>

      <Section title="10. Disclaimers and limitation of liability">
        <p>The Service is provided "as is" without warranties of any kind, express or implied. To the maximum extent permitted by law, Trainix and its team are not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including any injury resulting from following a workout or nutrition plan generated by the Service.</p>
      </Section>

      <Section title="11. Changes to these terms">
        <p>We may update these Terms from time to time. If we make material changes, we'll let you know (for example, via an in-app notice) before they take effect. Continuing to use the Service after changes take effect means you accept the updated Terms.</p>
      </Section>

      <Section title="12. Contact">
        <p>Questions about these Terms? Reach us at <a className="link" href="mailto:support@trainix.app">support@trainix.app</a>.</p>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-bold text-strong">{title}</h2>
      <div className="space-y-3 text-sm leading-6 text-muted">{children}</div>
    </section>
  );
}
